### ISSUE TITLE
URL to ICR is out of date

### ISSUE THREAD

**Issue by emilknievel** [exercism/crystal#513]
https://github.com/exercism/crystal/blob/930d0d7cc1cc9560e9a68924bdefe720e2714d6e/docs/LEARNING.md?plain=1#L17

As I was peeking through the [How to Learn](https://exercism.org/docs/tracks/crystal/learning) page of the Crystal track I noticed that the URL to the ICR is out of date.

The new location is https://github.com/crystal-community/icr

Best regards.

**Comment by meatball133** [comment]
Good catch!

I am a bit unsure what to do with that link, since the icr repo as you said has moved. But in like 2021 the official Crystal lang got a repl. Problem is that unless you use homebrew you have to manually compile a Crystal version which supports the repl. And I am unsure if I should have a doc about that or just remove the link.

**Comment by ryanplusplus** [comment]
My vote is just to remove it. There are too many caveats right now and I think it will be more confusing than it's worth for someone new to Crystal.

**Comment by emilknievel** [comment]
I'm new to Crystal myself (just about to dive in :smiley:) but if there indeed exists an official repl I think that would be the more natural thing to use, rather than a stale third-party application.

**Comment by ryanplusplus** [comment]
> I'm new to Crystal myself (just about to dive in 😃) but if there indeed exists an official repl I think that would be the more natural thing to use, rather than a stale third-party application.

Even if you need to build Crystal from source to be able to use it? I don't disagree that it has value, but I think that might be a bit overwhelming for someone that's trying to learn.

**Comment by emilknievel** [comment]
I see your point. I guess I'm just so used to building things from source myself to realize it might be a bit too involved for some people, especially if they're new to programming. :laughing:

**Comment by meatball133** [comment]
I am personally not using a Crystal version compiled with the interpreter. Since you have to recompile every time you want to update the language.

I will leave you with a short step through tutorial if you like to install the repl:

Also I only recommend doing this if you are using Linux, if you are using mac I sorta just recommend using homebrew and windows I recommend wsl for the repl. 

Step 1: Install Crystal (not from source)
Step 2: Clone the Crystal-lang  repo from the 1.9 branch or main :https://github.com/crystal-lang/crystal/tree/release/1.9
Step 3: Run make with the argument `interpreter=1`.
Step 4: Assign the newly compiled language version as main version

Here is a doc from 2021 explaining the repl: https://crystal-lang.org/2021/12/29/crystal-i/

**Comment by meatball133** [comment]
Compling the language doesnt really require any crystal knowledge but you have to be used to your operating system and how to build apps from source. Since the experience isn't super user friendly
