### ISSUE TITLE
Crystal Analyzer generated feedback is not visible

### ISSUE THREAD

**Issue by Sterver47** [exercism/crystal#535]
I'm getting this text: "Our Crystal Analyzer generated this feedback when analyzing your solution." The number 5 (or whatever number) is next to the robot icon within the Iteration. However, I don't see any generated feedback shown. I noticed this several times. Is this a problem on my side (browser), or is something wrong with the Exercism showing the feedback? 

![image](https://github.com/exercism/crystal/assets/7881288/2335781d-e3cb-4d4e-b54c-24afdc52ed7d)

**Comment by meatball133** [comment]
Hi!

This is a know issue, the number says how many comments were generated, at the moment is the ameba comment (the warning kind, rest is working) is broken and sieve comment broken due to an issue in the template. I have a pr ready to ship with fixes and hopefully it will be merged tomorrow: https://github.com/exercism/website-copy/pull/2280

**Comment by Sterver47** [comment]
Oh great! I'm glad this is going to be fixed, hopefully soon :). Thank you!
